import StyleDictionary from 'style-dictionary';
import { mkdirSync } from 'fs';

mkdirSync('build', { recursive: true });

// ─── Helpers ─────────────────────────────────────────────────────────────────

function hexToKotlin(hex) {
  const clean = hex.replace('#', '').toUpperCase();
  // 8-char = AARRGGBB (already has alpha), 6-char = RRGGBB (prepend FF)
  if (clean.length === 8) return `Color(0x${clean})`;
  return `Color(0xFF${clean})`;
}

function hexToCss(hex) {
  const clean = hex.replace('#', '');
  if (clean.length === 8) {
    const a = (parseInt(clean.substring(0, 2), 16) / 255).toFixed(2);
    const r = parseInt(clean.substring(2, 4), 16);
    const g = parseInt(clean.substring(4, 6), 16);
    const b = parseInt(clean.substring(6, 8), 16);
    return `rgba(${r},${g},${b},${a})`;
  }
  return `#${clean}`;
}

function pad(str, len) {
  return str.padEnd(len);
}

// ─── Kotlin formatter ─────────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'kotlin/distopia-tokens',
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;

    const m3Light = all.filter(t => t.path[0] === 'm3' && t.path[1] === 'light');
    const m3Dark  = all.filter(t => t.path[0] === 'm3' && t.path[1] === 'dark');
    const wrLight = all.filter(t => t.path[0] === 'writeopia' && t.path[1] === 'light');
    const wrDark  = all.filter(t => t.path[0] === 'writeopia' && t.path[1] === 'dark');

    const COL_WIDTH = 44;

    const renderM3 = (tokens, prefix) =>
      tokens.map(t => `internal val ${pad(`${prefix}${t.path[2]}`, COL_WIDTH)} = ${hexToKotlin(t.$value ?? t.value)}`).join('\n');

    const renderWr = (tokens, prefix) =>
      tokens.map(t => `internal val ${pad(`${prefix}${t.path[2]}`, COL_WIDTH)} = ${hexToKotlin(t.$value ?? t.value)}`).join('\n');

    return [
      `package io.writeopia.theme`,
      ``,
      `import androidx.compose.ui.graphics.Color`,
      ``,
      `// ─── AUTO-GENERATED by Distopia Style Dictionary ──────────────────────────────`,
      `// Source: distopia/tokens/colors/*.json`,
      `// Run \`npm run build\` in the distopia repo to regenerate.`,
      `// DO NOT edit this file manually — edit the JSON tokens instead.`,
      ``,
      `// ─── M3 baseline — Light ──────────────────────────────────────────────────────`,
      renderM3(m3Light, 'md_light_'),
      ``,
      `// ─── M3 baseline — Dark ───────────────────────────────────────────────────────`,
      renderM3(m3Dark, 'md_dark_'),
      ``,
      `// ─── WriteopiaColors semantic — Light ─────────────────────────────────────────`,
      renderWr(wrLight, 'wr_light_'),
      ``,
      `// ─── WriteopiaColors semantic — Dark ──────────────────────────────────────────`,
      renderWr(wrDark, 'wr_dark_'),
      ``,
    ].join('\n');
  },
});

// ─── CSS formatter ────────────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'css/distopia-vars',
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;

    const m3Light = all.filter(t => t.path[0] === 'm3' && t.path[1] === 'light');
    const m3Dark  = all.filter(t => t.path[0] === 'm3' && t.path[1] === 'dark');
    const wrLight = all.filter(t => t.path[0] === 'writeopia' && t.path[1] === 'light');
    const wrDark  = all.filter(t => t.path[0] === 'writeopia' && t.path[1] === 'dark');

    const toCssName = (prefix, role) => {
      const slug = role.replace(/([A-Z])/g, '-$1').toLowerCase();
      return `${prefix}${slug}`;
    };

    const renderBlock = (theme, m3Tokens, wrTokens) => {
      const lines = [
        `[data-theme="${theme}"] {`,
        ...m3Tokens.map(t => `  ${toCssName('--md-', t.path[2])}: ${hexToCss(t.$value ?? t.value)};`),
        `  /* WriteopiaColors */`,
        ...wrTokens.map(t => `  ${toCssName('--wr-', t.path[2])}: ${hexToCss(t.$value ?? t.value)};`),
        `}`,
      ];
      return lines.join('\n');
    };

    return [
      `/* AUTO-GENERATED by Distopia Style Dictionary — do not edit manually */`,
      ``,
      renderBlock('light', m3Light, wrLight),
      ``,
      renderBlock('dark', m3Dark, wrDark),
      ``,
    ].join('\n');
  },
});

// ─── Style Dictionary config ──────────────────────────────────────────────────

const sd = new StyleDictionary({
  source: ['tokens/colors/*.json'],
  platforms: {
    kotlin: {
      buildPath: 'build/',
      files: [{
        destination: 'DistopiaTokens.kt',
        format: 'kotlin/distopia-tokens',
      }],
    },
    css: {
      buildPath: 'build/',
      files: [{
        destination: 'tokens.css',
        format: 'css/distopia-vars',
      }],
    },
  },
});

await sd.buildAllPlatforms();
console.log('\n✅  Build complete → build/DistopiaTokens.kt + build/tokens.css\n');
